name: Free VPS with 8GB RAM and Saved Storage

on:
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Update the package 📦
        run: sudo apt update

      - name: Install QEMU, socat, and Tailscale ✅
        run: |
          set +e
          sudo apt install -y qemu-system qemu-utils socat curl wget zip xz-utils
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt update
          sudo apt install -y tailscale
        
          sudo tailscaled &
      - name: Free Disk Space (Quick)
        run: |
          sudo bash -c '
          rm -rf /opt/*
          for d in /usr/local/lib/android /usr/share/dotnet /opt/ghc \
            /usr/local/share/chromium /usr/local/share/firefox /usr/local/share/edge; do
            
            rm -rf $d
          done

          # Clean smaller caches normally
           rm -rf /opt/hostedtoolcache/* /tmp/* /var/tmp/*
           apt-get clean -y
           '
      - name: Download existing image or parts ⬇️
        env: 
          URL: ${{ secrets.URL }}
        run: |
          cd
          echo "Checking for saved parts on WebDAV..."
          PARTS=$(curl -s -u admin:admin $URL/webdav/ | grep -o 'windows_part_[a-z][a-z]' | sort | uniq)

          if [ -z "$PARTS" ]; then
            echo "⚠️ No saved parts found — fresh VM will be created."
          else
            echo "Found parts: $PARTS"
            for p in $PARTS; do
              echo "Downloading $p ..."
              curl -u admin:admin -O "$URL/webdav/$p"
            done
            echo "Rebuilding windows.img..."
            cat windows_part_* > windows.zip
            rm -rf windows_part_*
            unzip windows.zip
            rm -rf windows.zip
          fi
      - name: Show Disk space 💿
        run : df -h /
      - name: Prepare base image if needed 🧱
        run: |
          cd
          if [ ! -f "windows.img" ]; then
            echo "Creating new 20GB windows image..."
            qemu-img create -f raw windows.img 25G
            wget -O windows.iso "https://archive.org/download/tiny-10-23-h2/tiny10%20x64%2023h2.iso"
            touch cdrom
          fi

      - name: Boot the VM 🖥️
        run: |
          cd
          if [ -f "cdrom" ]; then
            sudo qemu-system-x86_64  \
              -enable-kvm -cpu host -m 8G \
              -hda windows.img\
              -cdrom windows.iso -vnc :2 -device e1000,netdev=net0 -netdev user,id=net0 -monitor unix:/tmp/qemu-monitor.sock,server,nowait -daemonize 
          else
            sudo qemu-system-x86_64  \
              -enable-kvm -cpu host -m 8G \
              -hda windows.img \
              -vnc :2 -device e1000,netdev=net0 -netdev user,id=net0 -monitor unix:/tmp/qemu-monitor.sock,server,nowait -daemonize  
          fi

      - name: Connect with Tailscale 🌐
        env:
          TS_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: sudo tailscale up --authkey $TS_AUTHKEY --accept-routes

      - name: Keep VM running 💤
        run: sleep 3600

      - name: Gracefully shutdown VM ⚙️
        run: |
          set +e
          sudo bash -c '
          sudo socat - UNIX-CONNECT:/tmp/qemu-monitor.sock <<< "system_powerdown"
          '

      - name: Compress and split image 📦
        run: |
          cd
          echo "Compressing alpine.img..."
          zip windows.zip windows.img
          rm -rf windows.img
          echo "Splitting into 1GB parts..."
          split -b 1024M windows.zip windows_part_

      - name: Upload parts to WebDAV ⬆️
        env :
          URL : ${{ secrets.URL }}
        run: |
          cd
          echo "Uploading parts to Render WebDAV..."
          for f in windows_part_*; do
            echo "Uploading $f ..."
            curl -u admin:admin -T "$f" "$URL/webdav/$f"
          done

          
